### ISSUE TITLE
Arrays display wrongly

### ISSUE THREAD

**Issue by UshakovVasilii** [sinsau/ng2-json-view#4]
html:
```html
<json-tree [json]="params" [expand]="false" [currExpand]="true" [label]="'Параметры'"></json-tree>
```
JSON:
``` js
{k1: ['val1', 123, {'a': 'b'}]}
```
displayed as:
![tree1](https://user-images.githubusercontent.com/3512063/45564747-1b562d00-b85a-11e8-8e53-d4b6b6d7f34f.png)

json-tree got `'val'`, `123` and `{'a':'b'}` as `[json]="obj"` here
https://github.com/sinsau/ng2-json-view/blob/master/src/lib/src/component/json.tree.html#L33

Should be something like:
```
0: val1
1: 123
2: {1}
    a: b
```

**Comment by UshakovVasilii** [comment]
Also sample
``` js
{a: [true, 'two', 3]}
```
![tree2](https://user-images.githubusercontent.com/3512063/45570044-11d4c100-b86a-11e8-8e54-d87a18713390.png)

**Comment by sinsau** [comment]
I'm bit busy... will look at it in couple of days.. and fix asap

**Comment by UshakovVasilii** [comment]
I created pull request
