### ISSUE TITLE
Old version in https://www.npmjs.com

### ISSUE THREAD

**Issue by UshakovVasilii** [sinsau/ng2-json-view#6]
I just modified src folder and didn't run any build scripts. Looks npmjs.com contain old js scripts

**Comment by sinsau** [comment]
v4.0.2 has all the changes.... make sure project is using latest version... "ng2-json-view": "^4.0.2"..

**Comment by UshakovVasilii** [comment]
4.0.1 has a problem, 4.0.2 fine. Thanks!
